[workspace]
channels = ["conda-forge", "bioconda"]
name = "primeseq"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = ">=3.12.9,<3.13"
fastqc = ">=0.12.1,<0.13"
multiqc = ">=1.28,<2"
cutadapt = ">=5.0,<6"
fastp = ">=0.24.0,<0.25"
#rseqc = ">=5.0.4"
#subread = ">=1.3.1,<2.0a0"